version: '3.7'
services:
  {% include "_cctmp/dash_name.txt" %}:
    build:
      context: '.'
      dockerfile: Dockerfile-build
    environment:
      - RAILS_ENV=${RAILS_ENV-development}
      - SAM_CLI_TELEMETRY=0
      - AWS_PROFILE=${AWS_PROFILE-default}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-us-east-1}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - ${HOME}/.aws:/root/.aws:delegated
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${PWD}:/var/task:delegated
      - /var/run/docker.sock:/var/run/docker.sock
