name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/bundle
            ./node_modules
          key: {{ "${{ runner.os }}-deploy-${{ hashFiles('Gemfile.lock', 'yarn.lock') }}" }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ "${{ secrets.AWS_ACCESS_KEY_ID }}" }}
          aws-secret-access-key: {{ "${{ secrets.AWS_SECRET_ACCESS_KEY }}" }}
          aws-region: us-east-1
      - name: Deploy
        uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/customink/{% include "_cctmp/dash_name.txt" %}-devcontainer
          cacheFrom: ghcr.io/customink/{% include "_cctmp/dash_name.txt" %}-devcontainer
          env: |
            CI
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./bin/deploy
