name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/bundle
            ./node_modules
          key: {{ "${{ runner.os }}-test-v1-${{ hashFiles('Gemfile.lock', 'yarn.lock') }}" }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: {{ "${{ github.repository_owner }}" }}
          password: {{ "${{ secrets.GITHUB_TOKEN }}" }}
      - name: Setup & Test
        uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/customink/{% include "_cctmp/dash_name.txt" %}-devcontainer
          cacheFrom: ghcr.io/customink/{% include "_cctmp/dash_name.txt" %}-devcontainer
          env: |
            CI
          runCmd: |
            ./bin/setup
            ./bin/test
